### PR TITLE
add 3 plot examples

### PR DESCRIPTION
**Pull request by jukent**
lines, scatter, and contour

### CODE REVIEW

**Comment by anissa111** [comment]
Ahh, we should add deployment previews to PRs

**Review by anissa111 — CHANGES_REQUESTED** [review]
I think we should be adding slightly more commentary on these. Also, are these actually adding anything on top of the matplotlib versions?

**Comment by jukent** [comment]
I updated the scatter plot. Before I fix contour and line, could you take a look and let me know if this is more what we want to target?

**Comment by anissa111** [comment]
> I updated the scatter plot. Before I fix contour and line, could you take a look and let me know if this is more what we want to target?

Yeah, I think this is way closer! I have a few notes:
- I think we should follow the matplotlib recommended way to generate the figures wherever we can, like:
```python
fig, ax = plt.subplots(figsize=(x, y))
ax.scatter(...)
```
- I like the iterative approach in your steps, but I think we could be a bit more granular. Like in the step where you add cartopy, you're also adding gridlines, a title, and axes labels. I think this could constitute its own step. I think we might also be able to get more detailed with the steps, maybe something like:
```md
# Scatter Plots

## Get station data

## How to make a simple scatter plot
### Base case (something with no customizations, just a plain call to scatter)
### Basic customizations (marker size, style, width, ect)

## Making a scatter plot with cartopy

## Adding color coding
### Base case (just default colorbar, automatic positioning)
### Colorbar customization

## Finishing touches
### Grid lines
### Titles and labels
```
- I don't think we need to default specify `edgecolor='lightgray'` and `facecolor='lightgray'` for the cartopy land feature, especially since (I think) the reason we have done that in the past is to match NCL style standards. I wouldn't be against showing that those are options, but I think we should consider leaving them out for any base cases we demonstrate in the spirit of minimal python lines/no stylistic recreation. Actually, I think this is true in general where reasonable, to demo plotting features with minimal additional inputs unless they're super standard (like `figsize` in `subplots` or `zorder`) and then add common or useful ones in a subsequent step.

- this is a small point, but it's hard to see the color info on the last plot since the markers are pretty small

**Comment by jukent** [comment]
@anissa111 I've incorporated your notes. Let me know when you've taken another look.

**Pull request closed without merging**
