### PR TITLE
Add pooch/geocat-comp for geocat-datafiles

### PR DESCRIPTION
**Pull request by cyschneck**
## PR Summary
Add `pooch`  and `geocat-comp` to conda env for working with `geocat-datafiles` in receipts

## Related Tickets & Documents
Adds new conda env for working with `geocat-datafiles` and `geocat-comp` for #101 

## PR Checklist
**General**
- [x] PR includes a summary of changes
- [x] Link relevant issues, make one if none exist

### CODE REVIEW

**Comment by anissa111** [comment]
I think we should also add the other environment change (`geocat-comp`) here

**Review by anissa111 — APPROVED** [review]

**Comment by kafitzgerald** [comment]
Pooch should get installed with geocat-datafiles.  Does it not?

**Comment by cyschneck** [comment]
When I was working on my local Jupyter notebook, it was prompting me to install pooch to be able to use datafiles, but I can see if it works locally if I install them separately

**Comment by kafitzgerald** [comment]
> When I was working on my local Jupyter notebook, it was prompting me to install pooch to be able to use datafiles, but I can see if it works locally if I install them separately

It won't hurt to have it explicitly listed here either.  I just want to make sure there's not an issue.  

I suspect it might be the packaging for geocat-datafiles.  Do you want to log an issue over on that repo w/ info how you installed it (e.g. conda, pip)?

**Comment by cyschneck** [comment]
Sure thing, I'll link to this issue, and give it a look separately. It could be a sign my dev env was out of date

**Pull request merged**
