### PR TITLE
Adding Google Analytics

### LINKED ISSUE #36: Set up some sort of web traffic analytics for github pages
As the project grows, I imagine it will become useful to know traffic stats for pages.

I believe Project Pythia does this with Google Analytics, but I think that may be overkill for our use case.

### PR DESCRIPTION
**Pull request by anissa111**
## PR Summary

~~This PR adds a `_templates` directory (the default location sphinx looks for, and the one we already had sphinx set up to look for in `config.py`) and `_templates/layout.html`, which adds the google analytics stuff by extending the default layout for all the generated html pages.~~

~~This is almost exactly what https://github.com/ProjectPythia/pythia-foundations/pull/123 did, though I don't believe that this will be a workaround for us, since the `sphinx_book_theme` to my knowledge does not support adding analytics like `jupyer_book_theme`~~

EDIT: See https://github.com/NCAR/geocat-applications/pull/89#pullrequestreview-2229140216 and https://github.com/NCAR/geocat-applications/pull/89#issuecomment-2277008320 for updated implementation method (thanks @kafitzgerald!)

Also, merging this will mean that we're adding tracking to preview urls, but only starting after this PR is merged. I don't think this matters, really, but it's something to know about.

## Related Tickets & Documents
Closes #36

## PR Checklist
**General**
- [x] PR includes a summary of changes
- [x] Link relevant issues, make one if none exist

### CODE REVIEW

**Comment by anissa111** [comment]
Also, just noting that I've never set up google analytics before, if something looks off, it's probably not intentional on my part!

**Comment by anissa111** [comment]
Oh wait I just realized something, hold on, sorry folks

**Review by jukent — APPROVED** [review]
Great @anissa111 thanks for demonstrating where you based this on and that it was in the local html pages as well as passing the preview. I am confident that this will work, and at the least not break anything if it doesn't for any reason.

**Review by kafitzgerald — COMMENTED** [review]
Since `sphinx-book-theme` inherits from `pydata-sphinx-theme` can we do something like [this](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/analytics.html#google-analytics)? 

```
html_theme_options["analytics"] = {
    "google_analytics_id": "G-XXXXXXXXXX",
}
```

I might be missing something though.  This is all a little new to me.

**Comment by anissa111** [comment]
I did see that, but I didn't check. Since it's not documented under the sphinx theme, I assumed it wouldn't work. 

I'll give it a shot!

**Review by kafitzgerald — APPROVED** [review]
🎉

Also, if you think it's better the other way around I'm happy to defer to you all.  Just figured I'd mention it.  

The layered nature of the theme docs isn't intuitive at all so I wasn't sure if it was just something you missed.

**Comment by anissa111** [comment]
Nah, this version is way more straightforward. If going through the theming ever gives us issues in the future, it won't be hard at all to switch to the more manual method I had here originally. 

I think I'm just a little (overly? unfairly?) distrustful of relying on sphinx theme features, haha.

**Review by jukent — APPROVED** [review]
Much neater :)

**Pull request merged**
